### ISSUE TITLE
Writes configuration error into the target source code

### ISSUE THREAD

**Issue by herring-swe** [microsoft/vscode-autopep8#201]
When run formatter on a python source file, the format ends with no obvious error but on closer inspection a line has been appened to the python source file:
```
unknown option 'max-complexity' ignored
```

autopep8 logs doesn't state any error

```
2023-11-25 19:58:30.840 [info] [Trace - 7:58:30 PM] Sending request 'textDocument/formatting - (2)'.
2023-11-25 19:58:30.844 [info] [Trace - 7:58:30 PM] Received notification 'window/logMessage'.
2023-11-25 19:58:30.845 [info] c:\Python\Python310\python.exe -m autopep8 -
2023-11-25 19:58:30.845 [info] [Trace - 7:58:30 PM] Received notification 'window/logMessage'.
2023-11-25 19:58:30.845 [info] CWD Server: d:\<retracted>
2023-11-25 19:58:30.986 [info] [Trace - 7:58:30 PM] Received response 'textDocument/formatting - (2)' in 145ms.
2023-11-25 19:58:30.989 [info] [Trace - 7:58:30 PM] Sending notification 'textDocument/didChange'.
```

I found the "max-complexity" in an butt old .pycodestyle in my user dir and it's probably invalid but not the point here.

For reproduction add this to %USERPROFILE%\\.pydevstyle
```
[pycodestyle]
max-complexity = 20
```

I expect a visible notification of the error or in the LOG and possibly a hint on where it reads the configuration.

> [!IMPORTANT]
> It is absolutely forbidden to put the error message in the source file!

ms-python.autopep8 version: 2023.8.0
Tested with with python 3.10.11 and python 3.8.10

**Comment by karthiknadig** [comment]
If `autopep8` does not give us an error there is no way for us to tell something went wrong. You can run the command that you see in the logs from the terminal like this:
```
> cd <your project dir>
> type <path-to-file> | python -m autopep8 -
```
That is exactly what we do, and if that prints out bad code then this is on autopep8 to fix.

**Comment by herring-swe** [comment]
I suggest you change that code to:
```
python -m autopep8 -i <path-to-file>
```
Then it will write the code in-place while printing all other message to stdout/stdout.
Another report on autopep8 has been reported here: https://github.com/hhatto/autopep8/issues/717

**Comment by karthiknadig** [comment]
In place writing is not an option, VS Code does several steps to formatting. When you save a file after editing it goes through a few steps, applies source fixes, applies import organization changes, and finally formats the code. All of this is done on the live editor buffer, this content is not on disk. Also, writing directly to disk can cause VS Code to lose undo history.

This is a bug in `autopep8` that is reporting to stdout than stderr as you mentioned in the bug here https://github.com/hhatto/autopep8/issues/717. 

Closing this against the upstream https://github.com/hhatto/autopep8/issues/717 . We update the bundled copy when there is a new release of autopep8 regularly.
